"""users table

Revision ID: 5cd886b914e2
Revises: 
Create Date: 2019-09-19 15:51:10.323205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd886b914e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Configuration',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('Value', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Configuration')
    # ### end Alembic commands ###
