"""Added crypto wallet config and manual assets tables

Revision ID: 633e9e9f08e6
Revises: 5cd886b914e2
Create Date: 2019-10-14 17:51:52.308595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633e9e9f08e6'
down_revision = '5cd886b914e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CryptoWalletConfig',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('Value', sa.String(length=255), nullable=True),
    sa.Column('Description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('CryptoWalletManualAssets',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Asset', sa.String(length=50), nullable=True),
    sa.Column('Amount', sa.Float(), nullable=True),
    sa.Column('Exchange', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CryptoWalletManualAssets')
    op.drop_table('CryptoWalletConfig')
    # ### end Alembic commands ###
