"""Added eth blockchain address

Revision ID: e5db6e89e764
Revises: 633e9e9f08e6
Create Date: 2019-10-14 18:32:38.990189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5db6e89e764'
down_revision = '633e9e9f08e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ETHBlockchainAddresses',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('Exchange', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ETHBlockchainAddresses')
    # ### end Alembic commands ###
